class ChatModel {
  final String name;
  final String msg;
  final String time;
  final String pic;

  ChatModel(this.name, this.msg, this.time, this.pic);
}

List<ChatModel> chatsData = [
  new ChatModel("Raj", "welcome to here", '10.30',
      "https://randomuser.me/api/portraits/men/0.jpg"),
  new ChatModel("Riyas", "where are you", '11.30',
      "https://randomuser.me/api/portraits/men/1.jpg"),
  new ChatModel("Khan", "how broo?", '10.30',
      "https://randomuser.me/api/portraits/men/3.jpg"),
  new ChatModel("Aadhil", "nice to meet you", '10.30',
      "https://randomuser.me/api/portraits/men/5.jpg"),
  new ChatModel("Sameer", "keelakarai", '10.30',
      "https://randomuser.me/api/portraits/men/7.jpg"),
  new ChatModel("Karthi", "diwali is coming", '0.30',
      "https://randomuser.me/api/portraits/men/8.jpg"),
  new ChatModel("Bala", "diwali crackers ?", '10.30',
      "https://randomuser.me/api/portraits/men/10.jpg"),
  new ChatModel("Ifthi", "you did't", '10.30',
      "https://randomuser.me/api/portraits/men/11.jpg"),
  new ChatModel("Nayeem", "i don't come", '10.30',
      "https://randomuser.me/api/portraits/men/76.jpg"),
  new ChatModel("Vimal", "full stack", '10.30',
      "https://randomuser.me/api/portraits/men/10.jpg"),
  new ChatModel("Raiyan", "athu sari", '10.30',
      "https://randomuser.me/api/portraits/men/40.jpg"),
  new ChatModel("Sundar", "take time for peace", '10.30',
      "https://randomuser.me/api/portraits/men/50.jpg"),
  new ChatModel("Esakki", "great things take time", '10.30',
      "https://randomuser.me/api/portraits/men/50.jpg"),
  new ChatModel("Raj", "welcome to here", '10.30',
      "https://randomuser.me/api/portraits/men/0.jpg"),
  new ChatModel("Riyas", "where are you", '11.30',
      "https://randomuser.me/api/portraits/men/1.jpg"),
  new ChatModel("Khan", "how broo?", '10.30',
      "https://randomuser.me/api/portraits/men/3.jpg"),
  new ChatModel("Aadhil", "nice to meet you", '10.30',
      "https://randomuser.me/api/portraits/men/5.jpg"),
  new ChatModel("Sameer", "keelakarai", '10.30',
      "https://randomuser.me/api/portraits/men/7.jpg"),
  new ChatModel("Karthi", "diwali is coming", '0.30',
      "https://randomuser.me/api/portraits/men/8.jpg"),
  new ChatModel("Bala", "diwali crackers ?", '10.30',
      "https://randomuser.me/api/portraits/men/10.jpg"),
  new ChatModel("Ifthi", "you did't", '10.30',
      "https://randomuser.me/api/portraits/men/11.jpg"),
  new ChatModel("Nayeem", "i don't come", '10.30',
      "https://randomuser.me/api/portraits/men/76.jpg"),
  new ChatModel("Vimal", "full stack", '10.30',
      "https://randomuser.me/api/portraits/men/10.jpg"),
  new ChatModel("Raiyan", "athu sari", '10.30',
      "https://randomuser.me/api/portraits/men/40.jpg"),
  new ChatModel("Sundar", "take time for peace", '10.30',
      "https://randomuser.me/api/portraits/men/50.jpg"),
  new ChatModel("Esakki", "great things take time", '10.30',
      "https://randomuser.me/api/portraits/men/50.jpg"),
];
